## Basics

In [1]:
import torch

In [2]:
torch.__version__

'2.0.1+cu117'

### Matrix 

In [3]:
x = torch.empty(2,3)
x

tensor([[8.5614e-29, 8.7861e-43, 8.5614e-29],
        [8.7861e-43, 8.6402e-29, 8.7861e-43]])

In [4]:
y = torch.rand(2,3)
y

tensor([[0.2667, 0.9031, 0.3458],
        [0.1231, 0.8511, 0.3880]])

In [5]:
z = torch.tensor([6,6,3])
z

tensor([6, 6, 3])

In [6]:
x = x.new_ones(2,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
x.size()

torch.Size([2, 3])

### Matrix Calculations

In [8]:
x+y

tensor([[1.2667, 1.9031, 1.3458],
        [1.1231, 1.8511, 1.3880]], dtype=torch.float64)

In [9]:
torch.add(x,y)

tensor([[1.2667, 1.9031, 1.3458],
        [1.1231, 1.8511, 1.3880]], dtype=torch.float64)

### View

In [10]:
x = torch.rand(4,4) 
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Numpy

In [11]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)